# Generated by Django 5.2.16 on 2026-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='carnet_igss',
            field=models.CharField(blank=True, help_text='Obligatorio para citas por COEX o Emergencia IGSS.', max_length=20, null=True, unique=True, verbose_name='carné de afiliación IGSS'),
        ),
    ]
