# Generated by Django 5.2.16 on 2026-08-17 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_paciente_carnet_igss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestudio',
            name='radiologos',
            field=models.ManyToManyField(blank=True, help_text='Al agendar una cita de este estudio, solo se podrá asignar a estos radiólogos.', limit_choices_to={'rol': 'medico_radiologo'}, related_name='tipos_estudio_asignados', to=settings.AUTH_USER_MODEL, verbose_name='radiólogos que realizan este estudio'),
        ),
    ]
