# Generated by Django 5.2.16 on 2026-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0019_asignar_radiologos_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita_asignada', 'Nueva cita asignada'), ('cita_confirmada', 'Cita confirmada'), ('cita_rechazada', 'Cita rechazada'), ('orden_pendiente', 'Nueva orden de trabajo pendiente'), ('estudio_listo_informar', 'Estudio listo para informar'), ('estudio_completado', 'Estudio completado'), ('datos_paciente_pendientes', 'Datos de paciente pendientes de llenar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
