# Generated by Django 5.2.16 on 2026-08-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0020_alter_notificacion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestudio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(
                default=30,
                help_text='Cuánto tiempo ocupa este estudio en el calendario de citas.',
                verbose_name='duración (minutos)',
            ),
        ),
    ]
