# Generated by Django 5.2.16 on 2026-08-21 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0021_tipoestudio_duracion_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='medico_referente',
            field=models.CharField(
                blank=True,
                help_text='Nombre del médico externo que refiere al paciente (para el reporte diario).',
                max_length=150, verbose_name='médico referente',
            ),
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                )),
                ('fecha', models.DateField()),
                ('convenio', models.CharField(
                    choices=[
                        ('coex', 'COEX'), ('privado', 'Privado'), ('emergencia_igss', 'Emergencia IGSS'),
                    ],
                    max_length=20,
                )),
                ('estado', models.CharField(
                    choices=[('borrador', 'Borrador'), ('enviado', 'Enviado')],
                    default='borrador', max_length=20,
                )),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                    related_name='reportes_diarios_enviados', to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'reporte diario',
                'verbose_name_plural': 'reportes diarios',
                'db_table': 'reportes_diarios',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'convenio')},
            },
        ),
    ]
