# Generated by Django 5.2.16 on 2026-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0023_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_emergencia_forzada',
            field=models.BooleanField(default=False, help_text='La recepcionista confirmó que agendó esta cita a propósito en un horario ya ocupado, por tratarse de una emergencia.', verbose_name='agendada como emergencia'),
        ),
    ]
