# Generated by Django 5.2.16 on 2026-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('administrador', 'Administrador'),
                    ('administrador_financiero', 'Administrador financiero'),
                    ('recepcionista', 'Recepcionista'),
                    ('tecnico_imagenes', 'Técnico de imágenes'),
                    ('medico_radiologo', 'Médico radiólogo'),
                    ('medico_remitente', 'Médico remitente'),
                ],
                default='administrador', max_length=25, verbose_name='rol',
            ),
        ),
    ]
