# Generated by Django 5.2.16 on 2026-08-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('crear_estudio', 'Creación de estudio'), ('editar_estudio', 'Edición de estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('adjuntar_informe', 'Carga de informe'), ('registrar_ticket', 'Registro de ticket de emergencia'), ('procesar_ticket', 'Procesamiento de ticket (genera orden de trabajo)'), ('enviar_reporte_diario', 'Envío de reporte diario')], max_length=30),
        ),
    ]
